// Header icons
export { ServerIcon } from './ServerIcon';
export { CloudIcon } from './CloudIcon';
export { NotificationIcon } from './NotificationIcon';

// Simple icons
export { UpIcon } from './UpIcon';
export { DownIcon } from './DownIcon';
export { EqualIcon } from './EqualIcon';

// Design System icons
export type { IconProps } from './DsIcons';
export {
  IcArrowDown,
  IcArrowUp,
  IcArrowRight,
  IcArrowLeft,
  IcChartS,
  IcChartM,
  IcChartL,
  IcChart01,
  IcChart02,
  IcChart03,
  IcChart04,
  IcChart05,
  IcChart06,
  IcChart07,
  IcChart08,
  IcMinus,
  IcPlus,
  IcCheck,
  IcReload,
  IcEye,
  IcEyeOff,
  IcMore,
  IcExpansion,
  IcMove,
  IcSearch,
  IcInputDelete,
  IcPower,
  IcActive,
  IcDeActive,
  IcSkipBack,
  IcSkipForward,
  IcHistory,
  IcEdit,
  IcCopyPage,
  IcCopy,
  IcDelete,
  IcSetting,
  IcDetail,
  IcNotice,
  IcFailCircle,
  IcTooltip,
  IcCheckCircle,
  IcExtend,
  IcLoad,
  IcTextarea,
  IcDownload,
  IcCalendar,
  IcDashboard,
  IcStorage,
  IcPurge,
  IcAlarmOff,
  IcGroup,
  IcPolicy,
  IcCert,
  IcReport,
  IcCloudUp,
  IcUpload,
  IcShare,
  IcUserManage,
  IcErrorTriangle,
  IcClose,
  IcAlarmOn,
  IcFilter,
  IcArrowRise,
  IcCloudDown,
  IcElectCount,
  IcGoMove,
  IcTarget,
  IcPeoples,
  IcLightning,
  IcDeCheck,
  IcList,
  IcFacade,
  IcBox,
  IcSorting,
  IcSidebarFold,
  IcSidebarOpen,
  IcResource,
  IcRefresh,
  IcTotal,
  IcCulSearch,
  IcTemplate,
  IcReduce,
  IcThumbUp,
  IcThumbDown,
  IcChatN,
  IcPaper,
  IcDomainOn,
  IcDomainOff,
  IcRecentEdit,
  IcComputer,
  IcWindows,
  IcLinux,
  IcZoomIn,
  IcZoomOut,
  IcFocus,
  IcMap,
  IcFullscreen,
  IcFullscreenExit,
  IcExceptionRule,
  IcRobot,
  // 22px versions
  IcArrowDown22,
  IcArrowUp22,
  IcArrowRight22,
  IcArrowLeft22,
  IcAlarmOff22,
  IcDownload22,
  IcFilterSlider22,
  IcMove22,
  IcNotice22,
  IcTooltip22,
  IcCheckCircle22,
  IcFailCircle22,
  IcCloudUp22,
  IcErrorTriangle22,
  IcPlus22,
  IcClose22,
  IcCheck22,
  IcDeCheck22,
  IcHistory22,
  IcEdit22,
  IcDetail22,
  IcCopyPage22,
  IcCopy22,
  IcDelete22,
  IcSetting22,
  IcInputDelete22,
  IcDashboardGrid22,
  IcSearch22,
  IcReload22,
  IcNextFuture22,
  IcPreOld22,
  IcShare22,
  IcCalendar22,
  IcChartS22,
  IcChartM22,
  IcChartL22,
  IcChart0122,
  IcChart0222,
  IcChart0322,
  IcChart0422,
  IcChart0522,
  IcChart0622,
  IcChart0722,
  IcChart0822,
  IcDashboard22,
  IcStorage22,
  IcPurge22,
  IcGroup22,
  IcPolicy22,
  IcCert22,
  IcReport22,
  IcUpload22,
  IcUserManage22,
  IcExtend22,
  // 28px versions
  IcArrowRise28,
  IcCloudDown28,
  IcElectCount28,
  IcCloudUp28,
  IcNotice28,
  IcCheckCircle28,
  IcFailCircle28,
  IcGoMove28,
  IcErrorTriangle28,
  IcTarget28,
  IcPeoples28,
  IcLightning28,
  IcBox28,
  IcEdit28,
  IcReport28,
  IcShare28,
  IcFacade28,
  IcDomainOff28,
  IcAlarmClock28,
  IcAlarmOn28,
  // ETC special elements
  IcHamburger,
  IcSeverityTriangleUp,
  IcSeverityTriangleDown,
  // ETC 40px icons
  IcNoData,
} from './DsIcons';

// ─── Icon Namespace ────────────────────────────────────────
// Usage: import { Icon } from '@happy2870/dsk/components/icons'
//        <Icon.Edit size={20} />
import { ServerIcon as _Server } from './ServerIcon';
import { CloudIcon as _Cloud } from './CloudIcon';
import { NotificationIcon as _Notification } from './NotificationIcon';
import { UpIcon as _Up } from './UpIcon';
import { DownIcon as _Down } from './DownIcon';
import { EqualIcon as _Equal } from './EqualIcon';
import * as Ds from './DsIcons';

export const Icon = {
  // Standalone icons
  Server: _Server,
  Cloud: _Cloud,
  Notification: _Notification,
  Up: _Up,
  Down: _Down,
  Equal: _Equal,
  // Design System 16px
  ArrowDown: Ds.IcArrowDown,
  ArrowUp: Ds.IcArrowUp,
  ArrowRight: Ds.IcArrowRight,
  ArrowLeft: Ds.IcArrowLeft,
  ChartS: Ds.IcChartS,
  ChartM: Ds.IcChartM,
  ChartL: Ds.IcChartL,
  Chart01: Ds.IcChart01,
  Chart02: Ds.IcChart02,
  Chart03: Ds.IcChart03,
  Chart04: Ds.IcChart04,
  Chart05: Ds.IcChart05,
  Chart06: Ds.IcChart06,
  Chart07: Ds.IcChart07,
  Chart08: Ds.IcChart08,
  Minus: Ds.IcMinus,
  Plus: Ds.IcPlus,
  Check: Ds.IcCheck,
  Reload: Ds.IcReload,
  Eye: Ds.IcEye,
  EyeOff: Ds.IcEyeOff,
  More: Ds.IcMore,
  Expansion: Ds.IcExpansion,
  Move: Ds.IcMove,
  Search: Ds.IcSearch,
  InputDelete: Ds.IcInputDelete,
  Power: Ds.IcPower,
  Active: Ds.IcActive,
  DeActive: Ds.IcDeActive,
  SkipBack: Ds.IcSkipBack,
  SkipForward: Ds.IcSkipForward,
  History: Ds.IcHistory,
  Edit: Ds.IcEdit,
  CopyPage: Ds.IcCopyPage,
  Copy: Ds.IcCopy,
  Delete: Ds.IcDelete,
  Setting: Ds.IcSetting,
  Detail: Ds.IcDetail,
  Notice: Ds.IcNotice,
  FailCircle: Ds.IcFailCircle,
  Tooltip: Ds.IcTooltip,
  CheckCircle: Ds.IcCheckCircle,
  Extend: Ds.IcExtend,
  Load: Ds.IcLoad,
  Textarea: Ds.IcTextarea,
  Download: Ds.IcDownload,
  Calendar: Ds.IcCalendar,
  Dashboard: Ds.IcDashboard,
  Storage: Ds.IcStorage,
  Purge: Ds.IcPurge,
  AlarmOff: Ds.IcAlarmOff,
  Group: Ds.IcGroup,
  Policy: Ds.IcPolicy,
  Cert: Ds.IcCert,
  Report: Ds.IcReport,
  CloudUp: Ds.IcCloudUp,
  Upload: Ds.IcUpload,
  Share: Ds.IcShare,
  UserManage: Ds.IcUserManage,
  ErrorTriangle: Ds.IcErrorTriangle,
  Close: Ds.IcClose,
  AlarmOn: Ds.IcAlarmOn,
  Filter: Ds.IcFilter,
  ArrowRise: Ds.IcArrowRise,
  CloudDown: Ds.IcCloudDown,
  ElectCount: Ds.IcElectCount,
  GoMove: Ds.IcGoMove,
  Target: Ds.IcTarget,
  Peoples: Ds.IcPeoples,
  Lightning: Ds.IcLightning,
  DeCheck: Ds.IcDeCheck,
  List: Ds.IcList,
  Facade: Ds.IcFacade,
  Box: Ds.IcBox,
  Sorting: Ds.IcSorting,
  SidebarFold: Ds.IcSidebarFold,
  SidebarOpen: Ds.IcSidebarOpen,
  Resource: Ds.IcResource,
  Refresh: Ds.IcRefresh,
  Total: Ds.IcTotal,
  CulSearch: Ds.IcCulSearch,
  Template: Ds.IcTemplate,
  Reduce: Ds.IcReduce,
  ThumbUp: Ds.IcThumbUp,
  ThumbDown: Ds.IcThumbDown,
  ChatN: Ds.IcChatN,
  Paper: Ds.IcPaper,
  DomainOn: Ds.IcDomainOn,
  DomainOff: Ds.IcDomainOff,
  RecentEdit: Ds.IcRecentEdit,
  Computer: Ds.IcComputer,
  Windows: Ds.IcWindows,
  Linux: Ds.IcLinux,
  ZoomIn: Ds.IcZoomIn,
  ZoomOut: Ds.IcZoomOut,
  Focus: Ds.IcFocus,
  Map: Ds.IcMap,
  Fullscreen: Ds.IcFullscreen,
  FullscreenExit: Ds.IcFullscreenExit,
  ExceptionRule: Ds.IcExceptionRule,
  Robot: Ds.IcRobot,
  // 22px
  ArrowDown22: Ds.IcArrowDown22,
  ArrowUp22: Ds.IcArrowUp22,
  ArrowRight22: Ds.IcArrowRight22,
  ArrowLeft22: Ds.IcArrowLeft22,
  AlarmOff22: Ds.IcAlarmOff22,
  Download22: Ds.IcDownload22,
  FilterSlider22: Ds.IcFilterSlider22,
  Move22: Ds.IcMove22,
  Notice22: Ds.IcNotice22,
  Tooltip22: Ds.IcTooltip22,
  CheckCircle22: Ds.IcCheckCircle22,
  FailCircle22: Ds.IcFailCircle22,
  CloudUp22: Ds.IcCloudUp22,
  ErrorTriangle22: Ds.IcErrorTriangle22,
  Plus22: Ds.IcPlus22,
  Close22: Ds.IcClose22,
  Check22: Ds.IcCheck22,
  DeCheck22: Ds.IcDeCheck22,
  History22: Ds.IcHistory22,
  Edit22: Ds.IcEdit22,
  Detail22: Ds.IcDetail22,
  CopyPage22: Ds.IcCopyPage22,
  Copy22: Ds.IcCopy22,
  Delete22: Ds.IcDelete22,
  Setting22: Ds.IcSetting22,
  InputDelete22: Ds.IcInputDelete22,
  DashboardGrid22: Ds.IcDashboardGrid22,
  Search22: Ds.IcSearch22,
  Reload22: Ds.IcReload22,
  NextFuture22: Ds.IcNextFuture22,
  PreOld22: Ds.IcPreOld22,
  Share22: Ds.IcShare22,
  Calendar22: Ds.IcCalendar22,
  ChartS22: Ds.IcChartS22,
  ChartM22: Ds.IcChartM22,
  ChartL22: Ds.IcChartL22,
  Chart0122: Ds.IcChart0122,
  Chart0222: Ds.IcChart0222,
  Chart0322: Ds.IcChart0322,
  Chart0422: Ds.IcChart0422,
  Chart0522: Ds.IcChart0522,
  Chart0622: Ds.IcChart0622,
  Chart0722: Ds.IcChart0722,
  Chart0822: Ds.IcChart0822,
  Dashboard22: Ds.IcDashboard22,
  Storage22: Ds.IcStorage22,
  Purge22: Ds.IcPurge22,
  Group22: Ds.IcGroup22,
  Policy22: Ds.IcPolicy22,
  Cert22: Ds.IcCert22,
  Report22: Ds.IcReport22,
  Upload22: Ds.IcUpload22,
  UserManage22: Ds.IcUserManage22,
  Extend22: Ds.IcExtend22,
  // 28px
  ArrowRise28: Ds.IcArrowRise28,
  CloudDown28: Ds.IcCloudDown28,
  ElectCount28: Ds.IcElectCount28,
  CloudUp28: Ds.IcCloudUp28,
  Notice28: Ds.IcNotice28,
  CheckCircle28: Ds.IcCheckCircle28,
  FailCircle28: Ds.IcFailCircle28,
  GoMove28: Ds.IcGoMove28,
  ErrorTriangle28: Ds.IcErrorTriangle28,
  Target28: Ds.IcTarget28,
  Peoples28: Ds.IcPeoples28,
  Lightning28: Ds.IcLightning28,
  Box28: Ds.IcBox28,
  Edit28: Ds.IcEdit28,
  Report28: Ds.IcReport28,
  Share28: Ds.IcShare28,
  Facade28: Ds.IcFacade28,
  DomainOff28: Ds.IcDomainOff28,
  AlarmClock28: Ds.IcAlarmClock28,
  AlarmOn28: Ds.IcAlarmOn28,
  // Special
  Hamburger: Ds.IcHamburger,
  SeverityTriangleUp: Ds.IcSeverityTriangleUp,
  SeverityTriangleDown: Ds.IcSeverityTriangleDown,
  NoData: Ds.IcNoData,
};
